[dcd]
src.git = "https://github.com/dlang-community/dcd"
fetch.github = "dlang-community/dcd"
git.fetchSubmodules = true
extract = ["dub.selections.json"]

[dfmt]
src.git = "https://github.com/dlang-community/dfmt"
fetch.github = "dlang-community/dfmt"

[serve-d]
src.git = "https://github.com/Pure-D/serve-d"
fetch.github = "Pure-D/serve-d"
extract = ["dub.selections.json"]
