[dcd]
src.github_tag = "dlang-community/dcd"
fetch.github = "dlang-community/dcd"
git.fetchSubmodules = true

[dfmt]
src.github_tag = "dlang-community/dfmt"
fetch.github = "dlang-community/dfmt"
# TODO: ask upstream to add their selections
# extract = ["dub.selections.json"]

[dscanner]
src.github_tag = "dlang-community/d-scanner"
fetch.github = "dlang-community/d-scanner"
extract = ["dub.selections.json"]

[dub]
src.github_tag = "dlang/dub"
fetch.github = "dlang/dub"

# [serve-d]
# src.github_tag = "pure-d/serve-d"
# fetch.github = "pure-d/serve-d"
# extract = ["dub.selections.json"]

[serve-d-bin-aarch64-darwin]
src.github_tag = "Pure-D/serve-d"
src.prefix = "v"
fetch.url = "https://github.com/Pure-D/serve-d/releases/download/v$ver/serve-d_$ver-osx-arm64.tar.xz"

[serve-d-bin-x86_64-darwin]
src.github_tag = "Pure-D/serve-d"
src.prefix = "v"
fetch.url = "https://github.com/Pure-D/serve-d/releases/download/v$ver/serve-d_$ver-osx-x86_64.tar.xz"

[serve-d-bin-x86_64-linux]
src.github_tag = "Pure-D/serve-d"
src.prefix = "v"
fetch.url = "https://github.com/Pure-D/serve-d/releases/download/v$ver/serve-d_$ver-linux-x86_64.tar.xz"
