# This file was generated by https://github.com/lionello/dub2nix v0.4.1
[ {
  fetch = {
    type = "git";
    url = "https://github.com/atilaneves/automem.git";
    rev = "v0.6.9";
    sha256 = "1iks18aj4y5nx8dwnab6jgz88f0lbi2p9wsydylnidpbzj2ryiwi";
    fetchSubmodules = false;
    date = "2023-02-16T17:00:24+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/1qkan4vkc2rxjqpzcq5jq05v0vhqkvdh-automem";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/etcimon/botan-math.git";
    rev = "v1.0.3";
    sha256 = "0jbpgpd1sjkp5075xh0k7m4m2d3yahi5scx3ql35fj4yns2mn2fq";
    fetchSubmodules = false;
    date = "2016-08-23T10:45:25-04:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/dic7r8jab936cgqc9fck032r49nvgv07-botan-math";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/s-ludwig/taggedalgebraic.git";
    rev = "v0.11.22";
    sha256 = "02iy90nwy0zzy25hwdqbcgd0w0lwzramcvi3pgyljhq0w0vl5hkq";
    fetchSubmodules = false;
    date = "2021-05-20T21:00:02+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/p8id0qb13j8pjdczflj2x35w6v63q4cx-taggedalgebraic";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/dlang/dub.git";
    rev = "v1.31.0";
    sha256 = "17lp6jrz7qs07x9wasdrxgz04f296zcfrb6f2xnws56nwwj0fbra";
    fetchSubmodules = false;
    date = "2023-02-01T17:13:01+00:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/n8s5cgym80gvf1c4kxash67aq6lnid8b-dub";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/containers.git";
    rev = "v0.9.0";
    sha256 = "0c0h8biz6xp7z4ixkqf6gici7cy4lpaynfl7ngkqiydz7x9ym74c";
    fetchSubmodules = false;
    date = "2021-09-22T16:21:01+00:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/fxwcy9g0xahcf4i7ijf9d928i4swvsin-containers";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/libmir/mir-core.git";
    rev = "v1.5.3";
    sha256 = "05xnk30r4fnq04szbzqs3bn5x28wlapbjxn00wm4in097l6g2gd5";
    fetchSubmodules = false;
    date = "2023-03-06T18:58:43+07:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/zgrx1s2ak33m6ryqid55xd52yqs8mhbf-mir-core";
  };
} {
  fetch = {
    type = "git";
    url = "https://gitlab.com/AntonMeep/silly.git";
    rev = "v1.1.1";
    sha256 = "0ywz5mnjzicgasffhikh51q1nydrvqz3kc34hakj98kiv7x1q256";
    fetchSubmodules = false;
    date = "2020-12-27T19:00:48+00:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/4y35bc89wvhiy1xaa0gcv4s58d5g3h9i-silly";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/DCD.git";
    rev = "v0.16.0-beta.1";
    sha256 = "1czm0av4m39535wkczwjg2hsil93kkyvysnrd3q7h1wrr8087irn";
    fetchSubmodules = false;
    date = "2023-03-16T16:45:25+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/vaz85n2j6fj2r6bq144gm8kspgp8p8qr-DCD";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/atilaneves/test_allocator.git";
    rev = "v0.3.3";
    sha256 = "0fim5sqxcj04s1idczrb252lqp89rb2cs3ffdz1m4k2xw6g0djrr";
    fetchSubmodules = false;
    date = "2021-03-23T22:33:17+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/ca5pq52p6dqc15agdlkvqwwlpj2a8drv-test_allocator";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/eventcore.git";
    rev = "v0.9.25";
    sha256 = "00x79mg9rvxy5r9110yff75mgbp7r3ankvi9j1i4rc1zyy4cgdva";
    fetchSubmodules = false;
    date = "2023-03-17T12:34:19+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/43vscialad1v55bim4dsy98km943w33p-eventcore";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/etcimon/libasync.git";
    rev = "v0.8.6";
    sha256 = "1pbvlfxbp3p0ld0552dzdl4ng5939f84drjbcj8a7g199p1ih045";
    fetchSubmodules = false;
    date = "2020-02-22T09:07:54-05:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/6l82qf5nav5pkbvnrhcs5v9vwj5xycq3-libasync";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/libmir/mir-algorithm.git";
    rev = "v3.18.4";
    sha256 = "1qhv3a035797ajz6wkcmz2bbn14xf9qaqccmlqvh6c69i9m69r30";
    fetchSubmodules = false;
    date = "2022-11-04T14:15:09+07:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/78w219ifjl19pwws4x7isza81db7vxpd-mir-algorithm";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/FreeSlave/standardpaths.git";
    rev = "v0.8.2";
    sha256 = "005arjsbf4rldp63kks3m9m80dxd774fk9hn4qli0451n0f4zx1n";
    fetchSubmodules = false;
    date = "2021-06-12T15:18:49+03:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/d0w8q2k26didrxpinvk5d9nz80vsjhyv-standardpaths";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe.d.git";
    rev = "v0.9.5";
    sha256 = "1cf8psyfxh7053wwcjm3jm9avyph6dkx7c4fahi0gr1lrflpvpcb";
    fetchSubmodules = false;
    date = "2022-07-18T17:27:21+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/dx5wdsw6rrwxrhg1vqx1a1p7jq89rz5g-vibe.d";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/Pure-D/DietComplete.git";
    rev = "v0.0.3";
    sha256 = "1vn0qlqg6qcj5n50dfql4dg8dqb31vcn8rx6f9cqvp4p5snazh7m";
    fetchSubmodules = false;
    date = "2019-07-10T00:15:25+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/6m2sl5raw130613hlslsag1vrmhjcdhh-DietComplete";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/etcimon/botan.git";
    rev = "v1.12.19";
    sha256 = "16s9lzmj2m1yb77nlyl99p9rvaiddn2afz4r9liajiygdmqakfiz";
    fetchSubmodules = false;
    date = "2020-08-19T13:56:38-04:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/0s6757ghz3qlh3z2nk4jbixmdqfn23s8-botan";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/libmir/mir-cpuid.git";
    rev = "v1.2.10";
    sha256 = "0kc1jr3drd7scgijv59yp2g6fcb7pcsm1yra1iikxavr6c1q62fs";
    fetchSubmodules = false;
    date = "2022-09-23T22:02:17+07:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/qkgigswm3xj2gkwc6lg431p0v68vhvdv-mir-cpuid";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/burner/inifiled.git";
    rev = "v1.3.3";
    sha256 = "1djnndy2s2vvv1myr4p0ypvg07fqzcxjah9jn1kjka5a3d8v09j4";
    fetchSubmodules = false;
    date = "2020-11-24T14:17:45+00:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/76xzfjbjkghy3gl2171agxjhkb9ccwm9-inifiled";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/dfmt.git";
    rev = "v0.15.0-beta.2";
    sha256 = "0szjnj51s1ggbj6rppvzdxdxvbq0hp68kjg0rsx9m9jcclbjby1x";
    fetchSubmodules = false;
    date = "2023-02-06T10:17:09+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/1wr4ja61dxyxbdijjarncqw099sk5yfi-dfmt";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe-core.git";
    rev = "v1.24.0";
    sha256 = "1d6zg8rxnachwcnvkr1x3qcwndd3n538rhyhshk6zppxd0w0b0js";
    fetchSubmodules = false;
    date = "2023-03-08T16:21:00+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/iiac4k8r607x76l6393b0hkb1n6yc9bb-vibe-core";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/ikod/dlang-requests.git";
    rev = "v2.0.9";
    sha256 = "0hxggc9s3byylm3pjff309shglyhj9sprf6sv0cfv3z19hx7mh5l";
    fetchSubmodules = false;
    date = "2022-10-22T14:12:50+03:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/av9y5bswzxx0k8xm6infd29ym1h4fnl7-dlang-requests";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/D-Scanner.git";
    rev = "v0.13.0";
    sha256 = "1zwsjigx4ys9yn639rdwyar56qfq43p401v97gvqf69ghm3x601k";
    fetchSubmodules = false;
    date = "2022-12-30T17:10:16+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/752h9f86p7iywikgqdcyiingrpcw5x4m-D-Scanner";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/rejectedsoftware/diet-ng.git";
    rev = "v1.8.1";
    sha256 = "11hrbvsxhipvcz9m1qlq92iaw0h35pzdy5rf7z8c4vx3hwjrnhni";
    fetchSubmodules = false;
    date = "2022-04-22T11:38:43+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/xziliy9ah3s3ah8mslnxsw47n4w6wkca-diet-ng";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/D-Programming-Deimos/openssl.git";
    rev = "v3.3.0";
    sha256 = "1yq9r9vq06zgsgimk0ziw4lbbjmps9shccb070yhag9hqhq75wlc";
    fetchSubmodules = false;
    date = "2023-02-18T13:09:29+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/6zdbfrj2qp3iymmjxdf5rk6qsvmxzhl9-openssl";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/libmir/mir-ion.git";
    rev = "v2.1.6";
    sha256 = "1qjf6hddvnn2b83iiw6fq2f48mnrwypv213mhg5cx1nya02zg27p";
    fetchSubmodules = false;
    date = "2023-02-12T15:03:15+07:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/zbkbbb0jlc0avjbnrkgsiyxrlh1n2vmk-mir-ion";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/FreeSlave/xdgpaths.git";
    rev = "v0.2.5";
    sha256 = "02cvyq2qbxp1sjsb5cgxljahi3ypw8kaibwad5av70nfqh3k80ix";
    fetchSubmodules = false;
    date = "2018-05-04T18:30:32+03:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/k8p9daqfrygs8m5ph42c0vbv83j6rb1n-xdgpaths";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/atilaneves/unit-threaded.git";
    rev = "v0.10.8";
    sha256 = "03yfvz3pqqa92aza84h43p8vfj7fn2ki8hz6hr1ihkqbyh32781b";
    fetchSubmodules = false;
    date = "2020-03-30T16:16:04-03:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/4wzpdj66r7ilqk54isx46k8jdkjvh7c9-unit-threaded";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/libdparse.git";
    rev = "v0.21.3";
    sha256 = "1bd7ix331bdblk0xsdggywfw8c1cab14rlhrb9pfvyf3wda1zlzz";
    fetchSubmodules = false;
    date = "2023-02-09T23:47:16+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/l3xl5sv9p22z58nk1smc0ip3xli3h015-libdparse";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/WebFreak001/rm-rf.git";
    rev = "v0.1.0";
    sha256 = "1pgrrl6fck7g84pjn3279grxxc8c7nlqqqwqswd3vfwvl4h0b5l7";
    fetchSubmodules = false;
    date = "2018-04-04T15:08:08+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/skkzifch7bz14blbs72g0kjrqa3y4lfi-rm-rf";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/etcimon/memutils.git";
    rev = "v1.0.9";
    sha256 = "08j9grn3l6gr275m392l0dfsx5ma6hs08gjfhh48hpy3v0bvb0ny";
    fetchSubmodules = false;
    date = "2023-03-02T15:19:28-05:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/glnf0ljd84mv6gzc9wgs1qq0vqqxvmzh-memutils";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/msgpack/msgpack-d.git";
    rev = "v1.0.4";
    sha256 = "1bvb1ha32lfpdj9a3cbpg2sd77dlw60iqx6avp48n3zi5jvhjk9i";
    fetchSubmodules = false;
    date = "2022-06-12T18:58:06+09:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/vda2w08i8g0fx8a0d1jyjcknwnp4n9i8-msgpack-d";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/wilzbach/stdx-allocator.git";
    rev = "v2.77.5";
    sha256 = "03av8zp5p6vf6fg005xbmwnjfw96jyrr4dcj4m56c4a3vx7v72pk";
    fetchSubmodules = false;
    date = "2018-12-23T13:54:22+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/b3h25asfh205wzwjfzjf2k2kkccpp96k-stdx-allocator";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/libddoc.git";
    rev = "v0.8.0";
    sha256 = "1ak98hnw4xr31mz6fz9x1mnayb4s15ip19b9ix0r4ya1qwxy0lj0";
    fetchSubmodules = false;
    date = "2021-05-20T21:30:48+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/ksvl74rbxn3fv2k0ir96haxalxxdplik-libddoc";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/ikod/cachetools.git";
    rev = "v0.4.1";
    sha256 = "1ixagsyn546ihjffr5glqgi10q05l63f4f8rvzdh10cp0m7lnrip";
    fetchSubmodules = false;
    date = "2022-12-17T18:37:33+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/is7jixhkxk0dy270cw04m22cinprw6g9-cachetools";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/WebFreak001/FuzzyMatch.git";
    rev = "v1.0.0";
    sha256 = "16xkhqshspm9izk2816iiipm2xsgxaczn6zxyfm8acckhbrs4zwa";
    fetchSubmodules = false;
    date = "2023-03-20T02:35:16+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/2h6lzp5k9665b9xljib8c8c55390y51y-FuzzyMatch";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/libmir/mir-linux-kernel.git";
    rev = "v1.0.1";
    sha256 = "1gcaavsni47352nvw9s41zkaswd582cafq3931i0zinhd9s3clag";
    fetchSubmodules = false;
    date = "2018-08-04T16:03:31+07:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/qz6axwci8kb1477j9dzgq85nscjfyvj1-mir-linux-kernel";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/FreeSlave/isfreedesktop.git";
    rev = "v0.1.1";
    sha256 = "0zxbpqhzk59qk5chpvf2mixh9ak52q3xvnchajqjm15zvf6y293r";
    fetchSubmodules = false;
    date = "2016-09-26T22:14:29+03:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/3di29hny5c9whj87gvpmxj6ijhsxy0np-isfreedesktop";
  };
} ]