# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dcd = {
    pname = "dcd";
    version = "8a693954d31c09fdfea3887b9bc75a6b66cfe9e7";
    src = fetchFromGitHub {
      owner = "dlang-community";
      repo = "dcd";
      rev = "8a693954d31c09fdfea3887b9bc75a6b66cfe9e7";
      fetchSubmodules = true;
      sha256 = "sha256-IztiRegaLPufB/das7f+i7TlObPHsf8tOUXpFqrMQ8E=";
    };
    "dub.selections.json" = builtins.readFile ./dcd-8a693954d31c09fdfea3887b9bc75a6b66cfe9e7/dub.selections.json;
    date = "2023-08-19";
  };
  dfmt = {
    pname = "dfmt";
    version = "1e765fb7819b58ee4501c51afbac9b1afa44d1e8";
    src = fetchFromGitHub {
      owner = "dlang-community";
      repo = "dfmt";
      rev = "1e765fb7819b58ee4501c51afbac9b1afa44d1e8";
      fetchSubmodules = false;
      sha256 = "sha256-AqyvoTPwmIuBxH+kKXIZcf29kaG5NPurZpszH3DOjR8=";
    };
    date = "2023-07-26";
  };
  serve-d = {
    pname = "serve-d";
    version = "c7ac3314a103c9c92b79b97a5e1556dc299fad23";
    src = fetchFromGitHub {
      owner = "Pure-D";
      repo = "serve-d";
      rev = "c7ac3314a103c9c92b79b97a5e1556dc299fad23";
      fetchSubmodules = false;
      sha256 = "sha256-p8kXQBC8CE7VQFIASOGAH1Y5yGdEWBVHb6l0o3HtGbo=";
    };
    "dub.selections.json" = builtins.readFile ./serve-d-c7ac3314a103c9c92b79b97a5e1556dc299fad23/dub.selections.json;
    date = "2023-09-01";
  };
  serve-d-bin-aarch64-darwin = {
    pname = "serve-d-bin-aarch64-darwin";
    version = "0.8.0-beta.14";
    src = fetchurl {
      url = "https://github.com/Pure-D/serve-d/releases/download/v0.8.0-beta.14/serve-d_0.8.0-beta.14-osx-arm64.tar.xz";
      sha256 = "sha256-KH61vEqBNX3Ixm5mi+bQ/Qc3KXrPd0DamEmkMxr4BPs=";
    };
  };
  serve-d-bin-x86_64-darwin = {
    pname = "serve-d-bin-x86_64-darwin";
    version = "0.8.0-beta.14";
    src = fetchurl {
      url = "https://github.com/Pure-D/serve-d/releases/download/v0.8.0-beta.14/serve-d_0.8.0-beta.14-osx-x86_64.tar.xz";
      sha256 = "sha256-d4SIM4M1QJFUIJRcgALe4Uwr3UAZB7lupq46rCK7RM4=";
    };
  };
  serve-d-bin-x86_64-linux = {
    pname = "serve-d-bin-x86_64-linux";
    version = "0.8.0-beta.14";
    src = fetchurl {
      url = "https://github.com/Pure-D/serve-d/releases/download/v0.8.0-beta.14/serve-d_0.8.0-beta.14-linux-x86_64.tar.xz";
      sha256 = "sha256-i5w56gqk+J6N6Iz9gwVvrZ06SH1Th67bQalK/RlxyQs=";
    };
  };
}
