# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dcd = {
    pname = "dcd";
    version = "v0.16.0-beta.2";
    src = fetchFromGitHub {
      owner = "dlang-community";
      repo = "dcd";
      rev = "v0.16.0-beta.2";
      fetchSubmodules = true;
      sha256 = "sha256-BWXuk4CYfhU98FeTXa/OeJGBLIdHJKGwedRceOH0Jhc=";
    };
    "dub.selections.json" = builtins.readFile ./dcd-v0.16.0-beta.2/dub.selections.json;
  };
  dfmt = {
    pname = "dfmt";
    version = "v0.15.1";
    src = fetchFromGitHub {
      owner = "dlang-community";
      repo = "dfmt";
      rev = "v0.15.1";
      fetchSubmodules = false;
      sha256 = "sha256-N2Tf1hydBVZ+TNjUORsBs8s57JFZ5LzOUobxRHkni7o=";
    };
  };
  serve-d-bin-aarch64-darwin = {
    pname = "serve-d-bin-aarch64-darwin";
    version = "0.8.0-beta.14";
    src = fetchurl {
      url = "https://github.com/Pure-D/serve-d/releases/download/v0.8.0-beta.14/serve-d_0.8.0-beta.14-osx-arm64.tar.xz";
      sha256 = "sha256-KH61vEqBNX3Ixm5mi+bQ/Qc3KXrPd0DamEmkMxr4BPs=";
    };
  };
  serve-d-bin-x86_64-darwin = {
    pname = "serve-d-bin-x86_64-darwin";
    version = "0.8.0-beta.14";
    src = fetchurl {
      url = "https://github.com/Pure-D/serve-d/releases/download/v0.8.0-beta.14/serve-d_0.8.0-beta.14-osx-x86_64.tar.xz";
      sha256 = "sha256-d4SIM4M1QJFUIJRcgALe4Uwr3UAZB7lupq46rCK7RM4=";
    };
  };
  serve-d-bin-x86_64-linux = {
    pname = "serve-d-bin-x86_64-linux";
    version = "0.8.0-beta.14";
    src = fetchurl {
      url = "https://github.com/Pure-D/serve-d/releases/download/v0.8.0-beta.14/serve-d_0.8.0-beta.14-linux-x86_64.tar.xz";
      sha256 = "sha256-i5w56gqk+J6N6Iz9gwVvrZ06SH1Th67bQalK/RlxyQs=";
    };
  };
}
