# This file was generated by https://github.com/lionello/dub2nix v0.4.0
[ {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/libdparse.git";
    rev = "v0.23.2";
    sha256 = "0051pl8g7wwcgyqzs8yi0yq366mmiqv423hblaml4x0bq5q6ny5g";
    fetchSubmodules = false;
    date = "2023-07-05T20:33:47+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/i8ysxxib53kknswghdin9k59xk6r24x4-libdparse";
  };
} ]