# This file was generated by https://github.com/lionello/dub2nix v0.4.1
[ {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/dsymbol.git";
    rev = "v0.14.1";
    sha256 = "0svqjl04ch7sql95p50icm5las0gvxj3s9vysvgqzxcvpls10x5k";
    fetchSubmodules = false;
    date = "2022-07-11T22:50:52+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/bbsb1x5kfbnnzgv82ry8hr8wzm2573qy-dsymbol";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/msgpack/msgpack-d.git";
    rev = "v1.0.4";
    sha256 = "1bvb1ha32lfpdj9a3cbpg2sd77dlw60iqx6avp48n3zi5jvhjk9i";
    fetchSubmodules = false;
    date = "2022-06-12T18:58:06+09:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/vda2w08i8g0fx8a0d1jyjcknwnp4n9i8-msgpack-d";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/wilzbach/stdx-allocator.git";
    rev = "v2.77.5";
    sha256 = "03av8zp5p6vf6fg005xbmwnjfw96jyrr4dcj4m56c4a3vx7v72pk";
    fetchSubmodules = false;
    date = "2018-12-23T13:54:22+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/b3h25asfh205wzwjfzjf2k2kkccpp96k-stdx-allocator";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/libdparse.git";
    rev = "v0.23.0";
    sha256 = "1qxm18sf75yxf70hykxfp2vhddnv8zrdivd67iq4xdw03rq08sh8";
    fetchSubmodules = false;
    date = "2023-05-04T04:22:30+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/7ky3ck2gksd838f2gx9yj2qj8dj5fk5m-libdparse";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/containers.git";
    rev = "v0.9.0";
    sha256 = "0c0h8biz6xp7z4ixkqf6gici7cy4lpaynfl7ngkqiydz7x9ym74c";
    fetchSubmodules = false;
    date = "2021-09-22T16:21:01+00:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/fxwcy9g0xahcf4i7ijf9d928i4swvsin-containers";
  };
} ]