# This file was generated by https://github.com/lionello/dub2nix v0.4.1
[ {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/containers.git";
    rev = "v0.9.0";
    sha256 = "0c0h8biz6xp7z4ixkqf6gici7cy4lpaynfl7ngkqiydz7x9ym74c";
    fetchSubmodules = false;
    date = "2021-09-22T16:21:01+00:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/fxwcy9g0xahcf4i7ijf9d928i4swvsin-containers";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/dsymbol.git";
    rev = "v0.13.0";
    sha256 = "06ci56fyh35jwzlsrvcg7f22p60ixlf2nzpkwyhnkcmi6kkshaj8";
    fetchSubmodules = false;
    date = "2022-02-07T23:16:20+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/2d1ynqbkq75r10s387gwwnmpfdy42m0j-dsymbol";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/DCD.git";
    rev = "v0.16.0-beta.2";
    sha256 = "1n5lf62axw6a83v965i8dw7nqs24cyzf4056p9zax0pq9mh0cqi5";
    fetchSubmodules = false;
    date = "2023-05-20T00:18:03+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/npj62jxzz1jskx6f7cf9gx9wgh6xn3mv-DCD";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/wilzbach/stdx-allocator.git";
    rev = "v2.77.5";
    sha256 = "03av8zp5p6vf6fg005xbmwnjfw96jyrr4dcj4m56c4a3vx7v72pk";
    fetchSubmodules = false;
    date = "2018-12-23T13:54:22+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/b3h25asfh205wzwjfzjf2k2kkccpp96k-stdx-allocator";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/libddoc.git";
    rev = "v0.8.0";
    sha256 = "1ak98hnw4xr31mz6fz9x1mnayb4s15ip19b9ix0r4ya1qwxy0lj0";
    fetchSubmodules = false;
    date = "2021-05-20T21:30:48+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/ksvl74rbxn3fv2k0ir96haxalxxdplik-libddoc";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/dlang-community/libdparse.git";
    rev = "v0.23.2";
    sha256 = "0051pl8g7wwcgyqzs8yi0yq366mmiqv423hblaml4x0bq5q6ny5g";
    fetchSubmodules = false;
    date = "2023-07-05T20:33:47+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/i8ysxxib53kknswghdin9k59xk6r24x4-libdparse";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/burner/inifiled.git";
    rev = "v1.3.3";
    sha256 = "1djnndy2s2vvv1myr4p0ypvg07fqzcxjah9jn1kjka5a3d8v09j4";
    fetchSubmodules = false;
    date = "2020-11-24T14:17:45+00:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/76xzfjbjkghy3gl2171agxjhkb9ccwm9-inifiled";
  };
} ]